name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: gradlew 실행 권한 설정
         run: chmod +x ./gradlew

      - name: gradle-wrapper.jar 읽기 권한 설정
         run: chmod 644 gradle/wrapper/gradle-wrapper.jar

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4   # ✅ 여기 v4 로 수정
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
